[package]
name = "mmf_sigil"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mmf_sigil"
path = "src/main.rs"

[[bin]]
name = "trainer"
path = "src/bin/trainer.rs"

[dependencies]
axum = { version = "0.8.4", features = ["macros"] }
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.42", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4", "serde"] }

base64 = "0.22.1"
aes-gcm = "0.10"
sha2 = "0.10"
zip = "4.3.0"
sled = "0.34"
figment = { version = "0.10", features = ["env", "toml"] }
log = "0.4"
toml = "0.9.4"
lazy_static = "1.4"
reqwest = { version = "0.12.22", features = ["blocking", "json"] }
thiserror = "2.0.12"
burn = { version = "0.18.0", features = ["train", "candle", "network"] }
burn-candle = "0.18.0"
burn-import = { version = "0.18.0", features = ["onnx"] }
indicatif = "0.18.0"
npyz = "0.8.3"
csv = "1.1"

# Cryptographic dependencies
ed25519-dalek = { version = "2.0", features = ["rand_core", "serde"] }
rand = "0.8"
getrandom = "0.2"
