# ===== Advisories =====
# All advisories are now errors by default. The `unmaintained` check is set
# to error on all crates, which is stricter than the original policy but safer.
[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
# The policy is to "warn" on unmaintained crates. With the new config format,
# this is achieved by ignoring the specific advisories.
ignore = [
    "RUSTSEC-2024-0384", # instant
    "RUSTSEC-2024-0436", # paste
]
unmaintained = "all"
yanked = "deny"

# ===== Licenses =====
# Licenses are denied by default unless explicitly allowed.
[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
  "ISC",
  "Zlib",
  "Unicode-3.0",
  "bzip2-1.0.6",
  "MPL-2.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
]
confidence-threshold = 0.92
exceptions = []
private = { ignore = true }

# ===== Bans =====
# Warn on duplicates for most crates, but deny for critical ones.
# Deny wildcards and the openssl stack.
[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = false
deny = [
  # Deny duplicates for critical crates
  { name = "serde", deny-multiple-versions = true },
  { name = "tokio", deny-multiple-versions = true },
  { name = "hyper", deny-multiple-versions = true },
  # Ban openssl stack in favor of rustls
  { name = "openssl" },
  { name = "openssl-sys" },
]
skip = []

# ===== Sources =====
[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
