# Sigil Protocol License File
# Generated on 2025-08-30 02:15:40 UTC
# Valid from 2025-08-30T02:15:40.522938900+00:00 until 2025-11-28T02:15:40.522938900+00:00

[license]
id = "sigil-license-b21ca81c87494d85b7c211ae488e782d"
issuedAt = "2025-08-30T02:15:40.522938900+00:00"
expiresAt = "2025-11-28T02:15:40.522938900+00:00"
loa = "Operator"
scope = ["canon:system", "module:builtin", "runtime:sigil"]
issuer = "sigil_trust_v1"
version = "1.0"

[license.owner]
name = "Carol Operator"
mnemonic = "Generated-b8ffeacb"
email = "carol@sigil.system"
hashId = "b8ffeacb1c3b6233"

[license.bindings]
canonFingerprint = "sha256:placeholder-will-be-computed-at-runtime"
runtimeId = "sigil-runtime-760965bdd02c4b16933869263bbb3dc8"

[license.trust]
trustModel = "sigil_trust_v1"
signature = "ed25519:placeholder-will-be-computed"
sealed = true

[license.permissions]
canMutateCanon = false
canOverrideAudit = false
canRegisterModule = true
canElevateIdentity = false

[license.audit]
lastVerified = "2025-08-30T02:15:40.522938900+00:00"
verifier = "sigil-license-generator"
canonicalized = true
