# Sigil Protocol License File
# Generated on 2025-08-30 02:15:34 UTC
# Valid from 2025-08-30T02:15:34.344796900+00:00 until 2025-11-28T02:15:34.344796900+00:00

[license]
id = "sigil-license-62645bf8f562413bbd3cb746dbd20385"
issuedAt = "2025-08-30T02:15:34.344796900+00:00"
expiresAt = "2025-11-28T02:15:34.344796900+00:00"
loa = "Mentor"
scope = ["canon:system", "module:builtin", "runtime:sigil"]
issuer = "sigil_trust_v1"
version = "1.0"

[license.owner]
name = "Bob Mentor"
mnemonic = "Generated-1061b689"
email = "bob@sigil.system"
hashId = "1061b6896d07e09d"

[license.bindings]
canonFingerprint = "sha256:placeholder-will-be-computed-at-runtime"
runtimeId = "sigil-runtime-a853852eec8b4cc4b152d62d03b210e3"

[license.trust]
trustModel = "sigil_trust_v1"
signature = "ed25519:placeholder-will-be-computed"
sealed = true

[license.permissions]
canMutateCanon = true
canOverrideAudit = false
canRegisterModule = true
canElevateIdentity = true

[license.audit]
lastVerified = "2025-08-30T02:15:34.344796900+00:00"
verifier = "sigil-license-generator"
canonicalized = true
